apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    common: todo-app
  ports:
    - name: todo-app-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: todo-app-backend
      protocol: TCP
      targetPort: 3001 # Port your app is running on inside the container ## services internal door
      port: 3001
