apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:  
      nodeSelector:
        kubernetes.io/hostname: k3d-mooc-agent-0
      containers:
        - name: todo-app-backend
          image: temibonn/todo-app-backend:v2.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: PORT_BACKEND
            - name: DOWNLOAD_DURATION
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: DOWNLOAD_DURATION
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: IMAGE_URL
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-secret
                  key: POSTGRES_PASSWORD
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cfg
                  key: RUST_LOG
