apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app-backend
  ports:
    - name: todo-app-backend
      protocol: TCP
      targetPort: 3001 # Port your app is running on inside the container ## services internal door
      port: 3001
