apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: todo-app-random-wiki-crnjb
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-app-random-wiki-crnjb
              image: temibonn/todo-app-random-wiki-cronjob:1.0
              imagePullPolicy: Always
              command:
                - /usr/local/bin/create_wiki_todo.sh
              env:
                - name: TODO_BACKEND_SERVICE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: todo-app-cfg
                      key: TODO_BACKEND_SERVICE_HOST
                - name: PORT_BACKEND
                  valueFrom:
                    configMapKeyRef:
                      name: todo-app-cfg
                      key: PORT_BACKEND
          restartPolicy: OnFailure

        
