apiVersion: batch/v1
kind: Cronjob
metadata:
  namespace: project
  name: todo-app-random-wiki-crnjb
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-app-random-wiki-crnjb
              image: temibonn/todo-app-random-wiki-crnjb:1.0
              imagePullPolicy: Always
              command:
                - /usr/local/bin/create_wiki_todo.sh
          restartPolicy: OnFailure

        
