[package]
name = "todo-app-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = {version = "0.8.9", features=["csr"]}
gloo-net = "0.6"
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
regex = "1.10"
