[package]
name = "todo-app-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = {version = "0.8.9", features=["csr"]}
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
dotenv = "0.15.0"
